# Generated by Django 5.2 on 2025-12-01 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends"),
                            ("only_me", "Only Me"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "message_privacy",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends"),
                            ("no_one", "No One"),
                        ],
                        default="everyone",
                        max_length=10,
                    ),
                ),
                ("last_seen_visible", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
